version: "3"
services:
  app:
    environment:
      - POSTGRES_HOST=192.168.1.71
    image: resturantapp-image
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=summer
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
